baseURL = "https://willschenk.com/"
languageCode = "en-us"
title = "Will Schenk"
theme="blankpage"

[params]
  description="My home on the internet"
  RSSSections = [ "Articles", "Microposts", "Photos" ]

  [[menu.main]]
    name = "Articles"
    weight = 1
  	identifier = "articles"
    url = "/articles/"
