baseURL = "https://willschenk.com/"
relativeURLs = true
pygmentsCodeFences = true
pygmentsUseClasses = true
languageCode = "en-us"
title = "Will Schenk"
description = "My home on the internet"
theme="bootstrap"

[params]
  description="My home on the internet"
  RSSSections = [ "Articles", "Microposts", "Photos" ]

  [[menu.main]]
    name = "About"
    weight = 1
    identifier = "about"
    url = "/about"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    name = "Articles"
    weight = 3
  	identifier = "articles"
    url = "/articles/"
