---
label: default
hide_body: false
is_partial: false
fields:
- type: text
  name: title
  label: title
  config:
    required: true
- type: text
  name: subtitle
  label: subtitle
- type: datetime
  name: date
  label: date
  config:
    date_format: yyyy/mm/dd
    required: true
- type: tag_list
  name: tags
  label: tags
